name: Package Build and Publish

on:
  push:
    branches:
    - fix/build
    tags:
    - v*

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: logger-cache-${{ runner.os }}
      - run: yarn install
      - run: yarn test
      - run: yarn build
      - name: Changes package from private to public
        run: |
          sed -i -e 's/"private":\s*true/"private": false/g' dist/package.json
      - run: npm ci
      - run: npm publish dist/ --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
